version: "3"
services:
  bt:
    image: ${BAOTA_IMAGE}
    container_name: bt
    ports:
      - "${BAOTA_HTTP_HOST_PORT}:80"
      - "${BAOTA_HTTPS_HOST_PORT}:443"
      - "${BAOTA_WEB_HOST_PORT}:8888"
      - "${BAOTA_MYSQL_WEB_HOST_PORT}:888"
      - "${BAOTA_MYSQL_HOST_PORT}:3306"
      - "${BAOTA_CONNECT_PORT}:20"
      - "${BAOTA_TRANSFER_PORT}:21"
    volumes:
      - ${SOURCE_DIR}:/mywww:rw
      - ${DATA_DIR}:/mydata:rw
    environment:
      TZ: "$TZ"
    restart: ${BAOTA_RESTART}
    networks:
      - default

networks:
  default:
